Backup/StatusMvc/Controllers/StatusReportController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Status.BLL;
using Status.Model;
using Status.Repository;
using StatusMvc.Models;
using NLog;

namespace StatusMvc.Controllers
{
    public class StatusReportController : Controller
    {
        private readonly Logger _logger = NLog.LogManager.GetCurrentClassLogger();

        private IStatusReportRepository _repository;
        private ITopicRepository _topicRepository;
        private IProjectRepository _projectRepository;
        private IResourceRepository _resourceRepository;
        private ITagRepository _tagRepository;
        private IStatusReportManager _statusReportManager;

        public StatusReportController(IStatusReportRepository repository, ITopicRepository topicRepository, IProjectRepository projectRepository, IResourceRepository resourceRepository, IStatusReportManager statusReportManager, ITagRepository tagRepository)
        {
            _repository = repository;
            _topicRepository = topicRepository;
            _projectRepository = projectRepository;
            _resourceRepository = resourceRepository;
            _tagRepository = tagRepository;
            _statusReportManager = statusReportManager;
            Mapper.CreateMap<StatusReport, StatusReportViewModel>()
                .ForMember(m => m.NumberOfStatusItems, opt => opt.ResolveUsing<NumberOfStatusItemsFormatter>());
            Mapper.CreateMap<StatusItem, StatusReportItemViewModel>()
                .ForMember(m => m.TagsString, opt =>
                {
                    opt.MapFrom(src =>
                        String.Join(",", (from tag in src.Tags
                                          select tag.Name)));
                    opt.NullSubstitute(String.Empty);
                }
                                      );

            Mapper.CreateMap<StatusReportItemViewModel, StatusItem>();

            Mapper.CreateMap<Project, ProjectViewModel>();

            Mapper.CreateMap<Tag, TagViewModel>();
            //.ForMember(m => m.StatusReportId, opt => opt.M);
            //.ForMember(dest => dest.ProjectLeadFullName, opt => opt.MapFrom(src => src.Project.Lead.FullName))
            //.ForMember(dest => dest.ProjectTeamLeadFullName, opt => opt.MapFrom(src => src.Project.Team.Lead.FullName));

        }

        public IStatusReportRepository StatusReportRepository
        {
            get { return _repository; }
        }

        public ITopicRepository TopicRepository
        {
            get { return _topicRepository; }
        }

        public IProjectRepository ProjectRepository
        {
            get { return _projectRepository; }
        }

        public IResourceRepository ResourceRepository
        {
            get { return _resourceRepository; }
        }

        public IStatusReportManager StatusReportManager
        {
            get { return _statusReportManager; }
        }

        public ITagRepository TagRepository
        {
            get { return _tagRepository; }
        }

        //
        // GET: /StatusReport/

        public ActionResult Index()
        {
            var statusDate = GetStatusDateFromQueryString();
            ViewBag.Message = String.Format("Status Report for {0:MM/dd/yyyy}",
                                            statusDate);
            return View();
        }

        private DateTime GetStatusDateFromQueryString()
        {
            DateTime statusDate;
            bool validDate = DateTime.TryParse(Request.QueryString["statusDate"], out statusDate);
            if (!validDate)
                statusDate = this.StatusReportRepository.GetActiveStatusReportDate();
            return statusDate;
        }

        public JsonResult GetAllStatusReports()
        {
            var data = StatusReportRepository.GetAllStatusReports();
            var vm = Mapper.Map<IList<StatusReport>, IList<StatusReportViewModel>>(data);

            return Json(vm, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetStatusReport(DateTime? statusDate)
        {
            var data = statusDate.HasValue ? StatusReportRepository.GetStatusReport(statusDate.Value) : StatusReportRepository.GetActiveStatusReport();
            // trim data
            //var lst = data.Items.ToList();
            //int count = 3;
            //lst.RemoveRange(count, data.Items.Count - count);
            //data.Items = lst;

            var vm = GetStatusReportViewModel(data);
            return Json(vm, JsonRequestBehavior.AllowGet);
        }

        private StatusReportViewModel GetStatusReportViewModel(StatusReport data)
        {
            var statusReportDate = data.PeriodStart;
            var vm = Mapper.Map<StatusReport, StatusReportViewModel>(data);
            // populate the recent dates
            if (vm != null)
                vm.StatusReportDates = this.StatusReportRepository.GetAllStatusReportDates();
            // determine whether we can roll status
            this.StatusReportManager.RollStatusDateProcessor.GetStatusReportDate(statusReportDate);
            DateTime statusRollDate;
            vm.CanRollStatus = this.StatusReportManager.CanRollStatusReport(data, out statusRollDate);
            if (vm.CanRollStatus) vm.RollStatusDate = statusRollDate;

            // get project names
            IList<Project> projects = this.ProjectRepository.GetAllProjects();
            vm.Projects = Mapper.Map<IList<Project>, IList<ProjectViewModel>>(projects);
            IList<Tag> tags = this.TagRepository.GetAllTags();
            vm.Tags = Mapper.Map<IList<Tag>, IList<TagViewModel>>(tags);
            //vm.Projects = this.ProjectRepository.GetAllProjects().Select(p => new {
            //    Name = p.Name, Id = p.Id, TeamLeadId = p.Team.Lead.Id }).ToList();
            return vm;
        }

        ////
        //// GET: /StatusReport/Details/5

        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        [HttpPost]
        public JsonResult RollStatus(StatusReportViewModel report)
        {
            // the following causes a problem - by reloading the status report from the database, we can't overwrite with 
            // objects being posted back by the client.  Either client provides all details of statusreport, or we go 
            // more manual on mapping back to actual objects.
            StatusReport sr = this.StatusReportRepository.Get(report.Id);
            this.StatusReportManager.StatusReportRepository = this.StatusReportRepository;
            var rolledReport = this.StatusReportManager.RollStatusReport(sr, GetAuditInfo());
            var vm = GetStatusReportViewModel(rolledReport);
            return Json(vm, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Save(StatusReportViewModel report)
        {
            // the following causes a problem - by reloading the status report from the database, we can't overwrite with 
            // objects being posted back by the client.  Either client provides all details of statusreport, or we go 
            // more manual on mapping back to actual objects.
            StatusReport sr = this.StatusReportRepository.Get(report.Id);

            using (var txn = this.StatusReportRepository.BeginTransaction())
            {
                if (report.Items != null)
                {
                    report.Items.ToList().ForEach(r =>
                                                      {
                                                          // need to map this back to status report
                                                          StatusItem sri = null;

                                                          // using Id won't work with multiple new entries
                                                          if (r.Id > 0)
                                                          { // is new
                                                              var srSource =
                                                                  (from srSourceItem in sr.Items
                                                                   where srSourceItem.Id == r.Id
                                                                   select srSourceItem).FirstOrDefault();
                                                              // map over the new item
                                                              sri = Mapper.Map<StatusReportItemViewModel, StatusItem>(r, srSource);
                                                          }
                                                          else
                                                          {
                                                              sri = Mapper.Map<StatusReportItemViewModel, StatusItem>(r);
                                                          }
                                                          sri.Milestone.Type = r.MilestoneType;

                                                          sri.AuditInfo =
                                                              GetAuditInfo();
                                                          // if topic doesn't exist yet, we should create
                                                          if (string.IsNullOrEmpty(sri.Caption))
                                                              throw new ArgumentNullException("Caption cannot be null!");
                                                          Topic topic = null;
                                                          if (r.TopicId != 0)
                                                              topic = this.TopicRepository.Get(r.TopicId);
                                                          else
                                                              topic =

Backup/StatusMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
    @*<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.9.0/build/reset-fonts/reset-fonts.css">
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.9.0/build/base/base-min.css">
    *@<link href='http://fonts.googleapis.com/css?family=Brawler' rel='stylesheet' type='text/css'>
    <link href="@Url.Content("~/Scripts/api/jquery.tagit.css")" rel="stylesheet" type="text/css" />
    @*<link href="@Url.Content("~/Scripts/api/tagit.ui-zendesk.css")" rel="stylesheet" type="text/css" />
    *@
    <script src="@Url.Content("~/Scripts/api/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/api/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/api/knockout-2.0.0.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/api/jquery-ui-1.8.16.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/api/jquery.autogrowtextarea.js")" type="text/javascript"></script>
    @*jquery.autoresize.js*@
    <script src="@Url.Content("~/Scripts/api/date.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/api/jquery.hotkeys.js")" type="text/javascript"></script>
    @*<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">*@
    <script src="@Url.Content("~/Scripts/api/tag-it.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/core/JqueryExt.js")" type="text/javascript"></script>
    @*<script src="@Url.Content("~/Scripts/api/jquery.tagsinput.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Scripts/api/jquery.tagsinput.css")" rel="stylesheet" type="text/css" />*@
    @RenderSection("HeadSection", false)
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>Status Again</h1>
            </div>

            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>

            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Status", "Index", "StatusReport")</li>
                    <li>@Html.ActionLink("Allocations", "Index", "ResourceAllocation")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>

            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

Backup/StatusMvc/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}